services:
  serverhub:
    build: .
    container_name: serverhub
    ports:
      - "5000:5000"
    volumes:

    restart: unless-stopped
    environment:
      - TZ=Europe/Vienna

volumes:
  serverhub_data:
